include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

unit test and feature test:
  stage: test
  image: python:3.11
  script:
    - !reference [.add repositories, script]
    - RUNLEVEL=1 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -y install ferm
    - pip install --no-cache-dir -r requirements/test.txt
    - pip install .
    - pytest -n 10 -vvv --cov-branch --cov=cyberfusion.FermSupport --cov-config=.coveragerc --cov-fail-under=100 --junitxml=report-pytest.xml --ci
  artifacts:
    reports:
      junit: report-*.xml
